### ISSUE TITLE
Specs

### ISSUE THREAD

**Issue by shawninder** [vigour-io/env#1]
Finish elaborating the desired API for this plugin, which provides static information, some of which can only be determined at run time. Although static, the plugin should still be an observable in order to be able to emit its `ready` event

**Comment by ninjatux** [comment]
check also #2 when writing specs

**Comment by ninjatux** [comment]
## Env Plugin Specs

The _Env Plugin_ should fill a `device` property of the bridge containing specific `env` informations. We should be able to get the following informations:
- **type**, device type, eg: `phone`, `tablet`
- **model**, device model, eg: `iPhone 6s`, `Android 4.4.4`
- **name**, device natural name eg: `marcus' iPhone`
- **os**, the os type eg: `android`, `iphone`
- **bundleId**, application unique id, eg: `com.awesomeapps.thebestapp`
- **version**, the app version, eg: `1.1.0`

@marcusbesjes can you review and validate this?

**Comment by michielibiza** [comment]
- After some talking with @youzi we decided to add language, region and country (country is where you are, region is the dialect of the language).
- In the example above of @ninjatux model will never return "android 4.4.4" but something like "LG-L70" I think we should add a `osVersion` field, on android it will have the sdk number (so 19 for android 4.4.4).
- I'll add a `versionCode` that is tied to the app `version`, but can be different.
- I don't know if we should have the `type = phone | tablet`. Android has hundreds of different screen sizes: which ones are phones and which ones tablets? furthermore the app already knows the screen size in 'logical units'.

Here is an object as android returns it currently what do you guys think? (cc @shawninder @avdwerff )

```
{  
  "bundleId":"io.vigour.plugin.example",
  "country":"nl",
  "language":"en",
  "languageRegion":"GB",
  "model":"LG-D320",
  "os":"Android",
  "osVersion":19,
  "version":"1.0",
  "versionCode":1
}
```

**Comment by shawninder** [comment]
Looks good to me. Can we make country, language and languageRegion observable? As in can we detect when the user changes his settings? I guess we could do that part later...

**Comment by ninjatux** [comment]
@michielibiza i can start making the plugin following the object passed by Android as a reference.

@avdwerff what can be retrieved for iOS?

**Comment by shawninder** [comment]
@ninjatux I've already started work on this. Checkout env#feature/refactor and wrapper#build-plugins
